#!/bin/sh

set -e

export RBENV_ROOT=/usr/local/rbenv
PATH=$RBENV_ROOT/shims:$RBENV_ROOT/bin:$PATH

cd "${0%/*}/.."

case "$1" in
start)
        bundle exec unicorn_rails -D -c config/unicorn.rb
        ;;
stop)
        kill -QUIT $(cat tmp/pids/unicorn.pid)
        ;;
reload)
        kill -USR2 $(cat tmp/pids/unicorn.pid)
        sleep 1
        kill -QUIT $(cat tmp/pids/unicorn.pid.oldbin)
        ;;
*)
        echo "Usage: $0 start|stop|reload" >&2
        exit 1
        ;;
esac
